

pipeline {
    agent any
    
    tools{
        jdk 'jdk'
        maven 'maven'
    }
    
    environment {
        SCANNER_HOME= tool 'sonar-scanner'
    }
    
    stages {
        stage('Git-Checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/pravin-hcl/DevOps_UseCase_Ekart.git'
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                withCredentials([
                    string(credentialsId: 'SONAR_URL', variable: 'SONAR_URL'),
                    string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TKN')
                ]){
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.url=${SONAR_URL} -Dsonar.login=${SONAR_TKN} -Dsonar.projectName=ekart \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=ekart '''
                }
                }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests=true'
            }
        }
        
        stage('Dockerhub') {
            steps {
                script{
                    // sh 'docker ps'
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh 'docker build -t ekart:latest -f docker/Dockerfile .'
                        sh 'docker tag ekart:latest pravinhcl/ekart:latest'
                        sh 'docker push pravinhcl/ekart:latest'
}
                }
            }
        }
        
        stage('Transfer Ansible Files') {
            steps {
                script {
                    sh 'scp -i /var/lib/jenkins/.ssh/id_rsa -o StrictHostKeyChecking=no -r ansible/ root@34.228.42.87:/home/ansible/workspace/CI-Pipeline'
                }
            }
        }
        stage('Deploy via Ansible') {
            steps {
                script {
                    sh 'ssh -i /var/lib/jenkins/.ssh/id_rsa -o StrictHostKeyChecking=no root@34.228.42.87 "cd /home/ansible/workspace/CI-Pipeline && ansible-playbook -i ansible/hosts ansible/deploy.yml"'
                }
            }
        }
               
    }
}
