---
- name: Deploy Docker Container
  hosts: docker_agents
  become: true
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: pravinhcl/ekart
        tag: latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: ekart-container
        image: pravinhcl/ekart:latest
        state: started
        ports:
          - "8070:8070"  # Map host port 8080 to container port 80


